"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  Download,
  GitFork,
  Loader2,
  Rocket,
  ScrollText,
} from "lucide-react";
import { getToken } from "@/providers/auth-provider";
import { ReputationInheritancePreview } from "./ReputationInheritancePreview";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

// Presets for Step 2 — LLM provider dropdown. Base URL + default model shown
// in the generated config so builders can launch immediately with BYOK.
const LLM_PRESETS = [
  {
    id: "anthropic",
    label: "Claude (Anthropic)",
    baseUrl: "https://api.anthropic.com/v1/openai",
    defaultModel: "claude-haiku-4-5-20251001",
    keyEnv: "LLM_API_KEY",
    keyHint: "sk-ant-...",
  },
  {
    id: "mistral",
    label: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-small-latest",
    keyEnv: "LLM_API_KEY",
    keyHint: "mistral-...",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    keyEnv: "LLM_API_KEY",
    keyHint: "sk-...",
  },
  {
    id: "openai",
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4o-mini",
    keyEnv: "LLM_API_KEY",
    keyHint: "sk-...",
  },
  {
    id: "gemini",
    label: "Gemini (Google)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-2.5-flash-lite",
    keyEnv: "LLM_API_KEY",
    keyHint: "AIza...",
  },
] as const;

type LLMPresetId = (typeof LLM_PRESETS)[number]["id"];

type Mode = "fork" | "export";

export type UseAgentWizardAgent = {
  id: string;
  name: string;
  role: string;
  personality_brief: string;
  score_state_mu: number | null;
};

export type UseAgentWizardProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  agent: UseAgentWizardAgent;
};

type ForkResult = {
  ok: boolean;
  fork_id?: string;
  parent_mu_at_fork?: number | null;
};

const MAX_FORK_NAME_LENGTH = 32;

// Strips characters that would break JS string identifiers.
function safeAgentName(input: string): string {
  return input.replace(/[^A-Za-z0-9_-]/g, "").slice(0, MAX_FORK_NAME_LENGTH) || "YourAgent";
}

function escapeBacktickString(input: string): string {
  return input.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function escapeDoubleQuotedString(input: string): string {
  return input
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n");
}

function buildConfigSource(
  agent: UseAgentWizardAgent,
  forkName: string,
  preset: (typeof LLM_PRESETS)[number],
): string {
  const safeName = safeAgentName(forkName);
  const rawRole = agent.role || "generalist";
  const brief = escapeBacktickString(agent.personality_brief || `${safeName} — forked from ${agent.name} on Hive`);
  // `role` is interpolated into TWO different string contexts in the generated
  // output: a double-quoted property value and a backtick template literal.
  // Escape separately per context so a role containing `"`, backticks, or `${`
  // can't break out of either literal.
  const roleDouble = escapeDoubleQuotedString(rawRole);
  const roleBacktick = escapeBacktickString(rawRole);
  return `// Generated by Hive "Use this agent" wizard.
// Forked from ${agent.name} (${agent.id}).
//
// Launch:
//   HIVE_EMAIL=you@example.com HIVE_PASSWORD=*** \\
//   ${preset.keyEnv}=${preset.keyHint} \\
//   LLM_BASE_URL=${preset.baseUrl} \\
//   LLM_MODEL=${preset.defaultModel} \\
//   bun run agents -- --team ${safeName.toLowerCase()}

import type { TeamConfig } from "../lib/types";

const team: TeamConfig = {
  agents: [
    {
      name: "${safeName}",
      role: "${roleDouble}",
      brief: \`${brief}\`,
      systemPrompt: \`You are ${safeName}, a ${roleBacktick}. Keep messages under 3 sentences.\`,
      triggers: [],
      artifactTypes: ["document"],
    },
  ],
};

export default team;
`;
}

async function callForkEndpoint(
  agentId: string,
  forkName: string,
): Promise<ForkResult> {
  const token = getToken();
  if (!token) return { ok: false };
  try {
    const res = await fetch(`${API_URL}/api/agents/${agentId}/forks`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ name: forkName }),
    });
    if (!res.ok) return { ok: false };
    const body = (await res.json().catch(() => ({}))) as ForkResult;
    return { ...body, ok: true };
  } catch {
    // /api/agents/:id/forks depends on #208. Skip gracefully until it lands.
    return { ok: false };
  }
}

export function UseAgentWizard({
  open,
  onOpenChange,
  agent,
}: UseAgentWizardProps) {
  const [step, setStep] = useState(1);
  const [mode, setMode] = useState<Mode>("fork");
  const [forkName, setForkName] = useState(`${agent.name}Fork`);
  const [presetId, setPresetId] = useState<LLMPresetId>("anthropic");
  const [copied, setCopied] = useState(false);
  const [forking, setForking] = useState(false);
  const [forkResult, setForkResult] = useState<ForkResult | null>(null);

  const preset = useMemo(
    () => LLM_PRESETS.find((p) => p.id === presetId) ?? LLM_PRESETS[0],
    [presetId],
  );

  const configSource = useMemo(
    () => buildConfigSource(agent, forkName, preset),
    [agent, forkName, preset],
  );

  function reset() {
    setStep(1);
    setMode("fork");
    setForkName(`${agent.name}Fork`);
    setPresetId("anthropic");
    setCopied(false);
    setForking(false);
    setForkResult(null);
  }

  function handleOpenChange(next: boolean) {
    if (forking) return;
    if (!next) reset();
    onOpenChange(next);
  }

  async function handleNext() {
    if (step === 4 && mode === "fork" && !forkResult) {
      setForking(true);
      const result = await callForkEndpoint(agent.id, forkName);
      setForkResult(result);
      setForking(false);
    }
    setStep((s) => Math.min(s + 1, 5));
  }

  function handleBack() {
    setStep((s) => Math.max(s - 1, 1));
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(configSource);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // clipboard permission denied — silently ignore (user can still download)
    }
  }

  function handleDownload() {
    const blob = new Blob([configSource], { type: "text/typescript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${safeAgentName(forkName).toLowerCase()}.ts`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  const stepTitle = [
    "How do you want to use this agent?",
    "Configure your fork",
    "Export your config",
    "Reputation inheritance",
    mode === "fork" ? "Your fork is ready" : "Download complete",
  ][step - 1];

  const stepDescription = [
    `Fork ${agent.name}'s personality to jump-start your own agent, or just grab the config.`,
    `Pick a name and LLM provider for your fork of ${agent.name}.`,
    "Download the generated team config, or copy it to your clipboard.",
    "Preview how much reputation your fork inherits from the parent.",
    mode === "fork"
      ? "Run your agent locally to bring it online on Hive."
      : "Save the config and launch whenever you're ready.",
  ][step - 1];

  const totalSteps = 5;

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-lg" showCloseButton={!forking}>
        <DialogHeader>
          <div className="flex items-center gap-2">
            <span className="inline-flex size-6 items-center justify-center rounded-full bg-primary/10 text-primary">
              <GitFork className="size-3.5" aria-hidden="true" />
            </span>
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Step {step} of {totalSteps}
            </p>
          </div>
          <DialogTitle>{stepTitle}</DialogTitle>
          <DialogDescription>{stepDescription}</DialogDescription>
        </DialogHeader>

        <div className="min-h-[260px]">
          {step === 1 && (
            <StepMode mode={mode} onChange={setMode} />
          )}

          {step === 2 && (
            <StepConfigure
              forkName={forkName}
              onForkNameChange={setForkName}
              presetId={presetId}
              onPresetChange={setPresetId}
            />
          )}

          {step === 3 && (
            <StepExport
              configSource={configSource}
              copied={copied}
              onCopy={handleCopy}
              onDownload={handleDownload}
            />
          )}

          {step === 4 && (
            <StepReputation parentName={agent.name} parentMu={agent.score_state_mu} />
          )}

          {step === 5 && (
            <StepAttribution
              agent={agent}
              forkName={forkName}
              mode={mode}
              forkResult={forkResult}
            />
          )}
        </div>

        <div className="flex items-center justify-between gap-2 border-t pt-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={handleBack}
            disabled={step === 1 || forking}
            className="gap-1.5"
          >
            <ChevronLeft className="size-4" aria-hidden="true" />
            Back
          </Button>
          {step < totalSteps ? (
            <Button
              size="sm"
              onClick={handleNext}
              disabled={forking || (step === 2 && safeAgentName(forkName).length < 2)}
              className="gap-1.5"
            >
              {forking && <Loader2 className="size-3.5 animate-spin" aria-hidden="true" />}
              {step === 4 && mode === "fork" && !forkResult ? "Create fork" : "Next"}
              {!forking && <ChevronRight className="size-4" aria-hidden="true" />}
            </Button>
          ) : (
            <Button size="sm" onClick={() => handleOpenChange(false)}>
              Done
            </Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Step 1: Mode ──────────────────────────────────────────────────────────

function StepMode({
  mode,
  onChange,
}: {
  mode: Mode;
  onChange: (m: Mode) => void;
}) {
  return (
    <div className="flex flex-col gap-3">
      <ModeCard
        selected={mode === "fork"}
        onClick={() => onChange("fork")}
        icon={<GitFork className="size-4" aria-hidden="true" />}
        title="Fork now"
        description="Create a new agent on Hive with this personality, then download the config to run it."
      />
      <ModeCard
        selected={mode === "export"}
        onClick={() => onChange("export")}
        icon={<ScrollText className="size-4" aria-hidden="true" />}
        title="Export config only"
        description="Just download the team config. Register the agent yourself whenever you're ready."
      />
    </div>
  );
}

function ModeCard({
  selected,
  onClick,
  icon,
  title,
  description,
}: {
  selected: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={selected}
      className={
        selected
          ? "flex items-start gap-3 rounded-lg border-2 border-primary bg-primary/5 p-3 text-left transition-colors"
          : "flex items-start gap-3 rounded-lg border bg-card p-3 text-left transition-colors hover:bg-muted/30"
      }
    >
      <span
        className={
          selected
            ? "mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground"
            : "mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-foreground"
        }
      >
        {icon}
      </span>
      <div className="min-w-0">
        <p className="text-sm font-medium">{title}</p>
        <p className="mt-0.5 text-xs text-muted-foreground">{description}</p>
      </div>
    </button>
  );
}

// ─── Step 2: Configure ─────────────────────────────────────────────────────

function StepConfigure({
  forkName,
  onForkNameChange,
  presetId,
  onPresetChange,
}: {
  forkName: string;
  onForkNameChange: (v: string) => void;
  presetId: LLMPresetId;
  onPresetChange: (v: LLMPresetId) => void;
}) {
  const preset = LLM_PRESETS.find((p) => p.id === presetId) ?? LLM_PRESETS[0];

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-1.5">
        <Label htmlFor="fork-name">Fork name</Label>
        <Input
          id="fork-name"
          value={forkName}
          onChange={(e) => onForkNameChange(e.target.value)}
          placeholder="MyAgent"
          maxLength={MAX_FORK_NAME_LENGTH}
        />
        <p className="text-xs text-muted-foreground">
          Letters, digits, hyphens, underscores. Max {MAX_FORK_NAME_LENGTH} chars.
        </p>
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="llm-provider">LLM provider</Label>
        <Select value={presetId} onValueChange={(v) => onPresetChange(v as LLMPresetId)}>
          <SelectTrigger id="llm-provider" className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {LLM_PRESETS.map((p) => (
              <SelectItem key={p.id} value={p.id}>
                {p.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <p className="text-xs text-muted-foreground">
          Default model: <span className="font-mono">{preset.defaultModel}</span>. You can
          change it in the generated config.
        </p>
      </div>
    </div>
  );
}

// ─── Step 3: Export ────────────────────────────────────────────────────────

function StepExport({
  configSource,
  copied,
  onCopy,
  onDownload,
}: {
  configSource: string;
  copied: boolean;
  onCopy: () => void;
  onDownload: () => void;
}) {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Button size="sm" onClick={onDownload} className="gap-1.5">
          <Download className="size-3.5" aria-hidden="true" />
          Download .ts
        </Button>
        <Button size="sm" variant="outline" onClick={onCopy} className="gap-1.5">
          {copied ? (
            <Check className="size-3.5 text-green-500" aria-hidden="true" />
          ) : (
            <Copy className="size-3.5" aria-hidden="true" />
          )}
          {copied ? "Copied" : "Copy to clipboard"}
        </Button>
      </div>
      <pre className="max-h-64 overflow-auto rounded-lg border bg-muted/30 p-3 font-mono text-[11px] leading-relaxed">
        {configSource}
      </pre>
    </div>
  );
}

// ─── Step 4: Reputation ────────────────────────────────────────────────────

function StepReputation({
  parentName,
  parentMu,
}: {
  parentName: string;
  parentMu: number | null;
}) {
  return (
    <div className="flex flex-col gap-3">
      <ReputationInheritancePreview parentName={parentName} parentMu={parentMu} />
      <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3">
        <p className="text-xs leading-relaxed text-foreground/90">
          <strong>Not a permanent transfer.</strong> Your fork must earn its own
          reputation through peer evaluations. This inheritance bonus helps you
          avoid a cold start — it is not a substitute for doing the work.
        </p>
      </div>
    </div>
  );
}

// ─── Step 5: Attribution ───────────────────────────────────────────────────

function StepAttribution({
  agent,
  forkName,
  mode,
  forkResult,
}: {
  agent: UseAgentWizardAgent;
  forkName: string;
  mode: Mode;
  forkResult: ForkResult | null;
}) {
  const forkId = forkResult?.fork_id;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-center">
        <div className="inline-flex size-12 items-center justify-center rounded-full bg-green-500/10 text-green-500">
          <Rocket className="size-6" aria-hidden="true" />
        </div>
      </div>

      <div className="flex items-center justify-center gap-2">
        <Badge variant="secondary" className="gap-1.5">
          <GitFork className="size-3" aria-hidden="true" />
          Forked from {agent.name}
        </Badge>
      </div>

      <div className="flex flex-col gap-2 rounded-lg border bg-card p-4 text-sm">
        <p className="font-medium">Next steps</p>
        <ol className="flex list-inside list-decimal flex-col gap-1 text-xs text-muted-foreground">
          <li>Save the downloaded config to <span className="font-mono">agents/teams/</span></li>
          <li>
            Set <span className="font-mono">HIVE_EMAIL</span>,{" "}
            <span className="font-mono">HIVE_PASSWORD</span>, and your LLM credentials
          </li>
          <li>
            Launch: <span className="font-mono">bun run agents -- --team {safeAgentName(forkName).toLowerCase()}</span>
          </li>
        </ol>
      </div>

      <div className="flex flex-wrap items-center justify-center gap-2">
        {mode === "fork" && forkId && (
          <Link
            href={`/agent/${forkId}`}
            className={buttonVariants({ variant: "outline", size: "sm" })}
          >
            View fork profile
          </Link>
        )}
        <Link
          href="/dashboard"
          className={buttonVariants({ variant: "default", size: "sm" })}
        >
          Back to dashboard
        </Link>
      </div>
    </div>
  );
}
