import type { Pool } from "pg";
import { json } from "../http/response";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SUPPORTED_FORMATS = new Set(["team-config"]);
const FILENAME_FALLBACK = "agent";

type AgentRow = {
  name: string;
  role: string;
  personality_brief: string | null;
  avatar_seed: string;
  builder_display_name: string;
  created_at: Date | string;
};

export async function handleAgentExport(
  agentId: string,
  format: string | null,
  pool: Pool
): Promise<Response> {
  if (!UUID_RE.test(agentId)) {
    return json({ error: "not_found", message: "Agent not found" }, 404);
  }
  if (!format || !SUPPORTED_FORMATS.has(format)) {
    return json(
      {
        error: "invalid_format",
        message: `Supported formats: ${[...SUPPORTED_FORMATS].join(", ")}`,
      },
      400
    );
  }

  const { rows } = await pool.query<AgentRow>(
    `SELECT a.name, a.role, a.personality_brief, a.avatar_seed, a.created_at,
            b.display_name AS builder_display_name
     FROM agents a
     JOIN builders b ON b.id = a.builder_id
     WHERE a.id = $1`,
    [agentId]
  );
  if (rows.length === 0) {
    return json({ error: "not_found", message: "Agent not found" }, 404);
  }

  const agent = rows[0];
  const brief = agent.personality_brief ?? "";
  const body = renderTeamConfig({
    name: agent.name,
    role: agent.role,
    brief,
    builderName: agent.builder_display_name,
    parentAgentId: agentId,
  });
  const slug = slugify(agent.name);

  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": "application/typescript; charset=utf-8",
      "Content-Disposition": `attachment; filename="personality-${slug}.ts"`,
      "Cache-Control": "private, no-store",
      "Access-Control-Allow-Origin": process.env.ALLOWED_ORIGIN || "*",
    },
  });
}

function slugify(raw: string): string {
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug.length > 0 ? slug : FILENAME_FALLBACK;
}

function renderTeamConfig(args: {
  name: string;
  role: string;
  brief: string;
  builderName: string;
  parentAgentId: string;
}): string {
  const seededPrompt = args.brief
    ? `You are ${args.name}, a ${args.role}. ${args.brief} Keep messages under 3 sentences.`
    : `You are ${args.name}, a ${args.role}. TODO: describe the personality and style.`;

  const today = new Date().toISOString().slice(0, 10);
  const header = [
    `// Generated by Hive on ${today} — fork of agent ${args.name} by ${args.builderName}.`,
    `// Parent agent id: ${args.parentAgentId}`,
    `// Drop this file into hive-starter-kit/src/personalities/ and customize`,
    `// systemPrompt, triggers, and artifactTypes to shape your agent's behavior.`,
    `// See docs/BYOK.md for the runtime configuration.`,
  ].join("\n");

  // JSON.stringify guarantees valid JS string literals (escapes quotes, newlines,
  // control chars). Double-quoted strings keep ${...} as a literal substring
  // rather than a template expression — no injection possible.
  const name = JSON.stringify(args.name);
  const role = JSON.stringify(args.role);
  const brief = JSON.stringify(args.brief);
  const systemPrompt = JSON.stringify(seededPrompt);

  return `${header}

import type { AgentPersonality } from "hive-starter-kit";

export const personality: AgentPersonality = {
  name: ${name},
  role: ${role},
  brief: ${brief},
  systemPrompt: ${systemPrompt},
  // TODO: add keywords that should wake your agent up in channel
  triggers: [],
  // TODO: choose from "ticket" | "spec" | "decision" | "component" | "pr" | "document"
  artifactTypes: [],
};

export default personality;
`;
}
